/**
 * Shared type definitions for TimePortal
 * These types are used across both the Electron main process and React renderer
 */

export interface LinkedJiraIssue {
    key: string;
    summary: string;
    issueType: string;
    status: string;
    projectKey: string;
    projectName: string;
}

export interface WorkAssignment {
    type: 'bucket' | 'jira';
    bucket?: {
        id: string;
        name: string;
        color: string;
    };
    jiraIssue?: LinkedJiraIssue;
}

export interface TimeBucket {
    id: string;
    name: string;
    color: string;
    parentId?: string | null;
    isFolder?: boolean;
    linkedIssue?: LinkedJiraIssue;
}

export interface WindowActivity {
    appName: string;
    windowTitle: string;
    timestamp: number;
    duration: number;
    screenshotPaths?: string[];
    screenshotDescriptions?: { [path: string]: string };
}

export interface TimeEntry {
    id: string;
    startTime: number;
    endTime: number;
    duration: number;
    assignment?: WorkAssignment;
    assignmentAutoSelected?: boolean;
    bucketId?: string | null;
    linkedJiraIssue?: LinkedJiraIssue;
    description?: string;
    descriptionAutoGenerated?: boolean;
    detectedTechnologies?: string[];
    detectedActivities?: string[];
    windowActivity?: WindowActivity[];
    screenshotPath?: string;
    tempoAccount?: {
        key: string;
        name: string;
        id: string;
    };
    tempoAccountAutoSelected?: boolean;
}
