import React, { createContext, useContext, useState, useEffect } from 'react';

export interface TempoWorkAttributeValue {
    key: string;
    value: string;
}

export interface TempoSettings {
    apiToken: string;
    baseUrl: string; // 'https://api.tempo.io' or 'https://api.eu.tempo.io'
    defaultIssueKey?: string; // Optional default Jira issue key
    enabled: boolean;
    workAttributes?: TempoWorkAttributeValue[]; // Configured work attributes
}

export interface JiraSettings {
    baseUrl: string; // 'https://your-domain.atlassian.net'
    email: string; // User email for basic auth
    apiToken: string; // Jira API token
    enabled: boolean;
    selectedProjects: string[]; // Array of project keys to fetch data from
}

export interface AISettings {
    autoGenerateDescription: boolean;  // Default: true
    autoAssignWork: boolean;           // Default: true
    autoSelectAccount: boolean;        // Default: true
    assignmentConfidenceThreshold: number;  // Default: 0.7 (70%)
    accountConfidenceThreshold: number;     // Default: 0.8 (80%)
}

export interface AppSettings {
    minActivityDuration: number; // milliseconds - activities shorter than this get filtered
    activityGapThreshold: number; // milliseconds - max gap between same-app activities to keep short ones
    tempo: TempoSettings;
    jira: JiraSettings;
    ai?: AISettings;
}

interface SettingsContextType {
    settings: AppSettings;
    updateSettings: (updates: Partial<AppSettings>) => void;
    resetSettings: () => void;
}

const defaultSettings: AppSettings = {
    minActivityDuration: 1000, // 1 second
    activityGapThreshold: 2 * 60 * 1000, // 2 minutes
    tempo: {
        apiToken: '6OpFKSmqq340DZ2vBYz4Adgb539JTr-us',
        baseUrl: 'https://api.tempo.io',
        defaultIssueKey: '',
        enabled: true,
        workAttributes: [],
    },
    jira: {
        baseUrl: 'https://beemhq.atlassian.net/',
        email: 'benoit.tanguay@beemhq.com',
        apiToken: 'ATATT3xFfGF0wS3u2J49jdrAfKVKTH1y2NgLW9A115REFkp3PSA1PnhJ8np6gSCFDJuQ2iKOn19xPVKSmzaZR5_KZKMTth9iy9U17UOnKwqLKKDhwA6pSxvHeTvC-jfPSK7Pyyq6oTeZmxX2cg0xxkvlQ73zrqQPZYVJ24pPatmJ745pZDBHbKA=A8489265',
        enabled: true,
        selectedProjects: ['DES', 'BEEM'],
    },
    ai: {
        autoGenerateDescription: true,
        autoAssignWork: true,
        autoSelectAccount: true,
        assignmentConfidenceThreshold: 0.7,
        accountConfidenceThreshold: 0.8,
    },
};

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

export const SettingsProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [settings, setSettings] = useState<AppSettings>(defaultSettings);
    const [isSecureStorageAvailable, setIsSecureStorageAvailable] = useState<boolean>(false);
    const [migrationComplete, setMigrationComplete] = useState<boolean>(false);

    // Check if secure storage is available
    useEffect(() => {
        const checkSecureStorage = async () => {
            try {
                const result = await window.electron.ipcRenderer.secureIsAvailable();
                setIsSecureStorageAvailable(result.available);
                console.log('[SettingsContext] Secure storage available:', result.available);
            } catch (error) {
                console.error('[SettingsContext] Failed to check secure storage:', error);
                setIsSecureStorageAvailable(false);
            }
        };
        checkSecureStorage();
    }, []);

    // Load settings and migrate credentials on mount
    useEffect(() => {
        const loadAndMigrateSettings = async () => {
            const stored = localStorage.getItem('timeportal-settings');
            let parsedSettings = defaultSettings;

            if (stored) {
                try {
                    parsedSettings = JSON.parse(stored);
                } catch (error) {
                    console.error('[SettingsContext] Failed to parse settings from localStorage:', error);
                    parsedSettings = defaultSettings;
                }
            }

            // If secure storage is available, try to load credentials from secure storage
            if (isSecureStorageAvailable) {
                try {
                    // Migrate credentials from localStorage to secure storage if they exist
                    if (parsedSettings.tempo?.apiToken && parsedSettings.tempo.apiToken !== defaultSettings.tempo.apiToken) {
                        console.log('[SettingsContext] Migrating Tempo API token to secure storage');
                        await window.electron.ipcRenderer.secureStoreCredential('tempo-api-token', parsedSettings.tempo.apiToken);
                        // Clear from localStorage
                        parsedSettings.tempo.apiToken = '';
                    }

                    if (parsedSettings.jira?.apiToken && parsedSettings.jira.apiToken !== defaultSettings.jira.apiToken) {
                        console.log('[SettingsContext] Migrating Jira API token to secure storage');
                        await window.electron.ipcRenderer.secureStoreCredential('jira-api-token', parsedSettings.jira.apiToken);
                        // Clear from localStorage
                        parsedSettings.jira.apiToken = '';
                    }

                    if (parsedSettings.jira?.email && parsedSettings.jira.email !== defaultSettings.jira.email) {
                        console.log('[SettingsContext] Migrating Jira email to secure storage');
                        await window.electron.ipcRenderer.secureStoreCredential('jira-email', parsedSettings.jira.email);
                        // Clear from localStorage
                        parsedSettings.jira.email = '';
                    }

                    // NOTE: We load credentials from secure storage for migration purposes,
                    // but continue using hardcoded defaults for testing until final release.
                    // When ready for production, uncomment the lines below to use secure credentials.

                    // const tempoTokenResult = await window.electron.ipcRenderer.secureGetCredential('tempo-api-token');
                    // const jiraTokenResult = await window.electron.ipcRenderer.secureGetCredential('jira-api-token');
                    // const jiraEmailResult = await window.electron.ipcRenderer.secureGetCredential('jira-email');

                    // Build settings with hardcoded defaults for testing
                    const mergedSettings: AppSettings = {
                        ...defaultSettings,
                        ...parsedSettings,
                        tempo: {
                            ...parsedSettings.tempo,
                            // Use hardcoded default for testing, or secure storage value if available
                            apiToken: defaultSettings.tempo.apiToken, // Keep hardcoded default
                            baseUrl: parsedSettings.tempo?.baseUrl || defaultSettings.tempo.baseUrl,
                            defaultIssueKey: parsedSettings.tempo?.defaultIssueKey || '',
                            enabled: parsedSettings.tempo?.enabled ?? defaultSettings.tempo.enabled,
                        },
                        jira: {
                            ...parsedSettings.jira,
                            // Use hardcoded defaults for testing, or secure storage values if available
                            baseUrl: parsedSettings.jira?.baseUrl || defaultSettings.jira.baseUrl,
                            email: defaultSettings.jira.email, // Keep hardcoded default
                            apiToken: defaultSettings.jira.apiToken, // Keep hardcoded default
                            enabled: parsedSettings.jira?.enabled ?? defaultSettings.jira.enabled,
                            selectedProjects: parsedSettings.jira?.selectedProjects || defaultSettings.jira.selectedProjects,
                        },
                    };

                    setSettings(mergedSettings);
                    setMigrationComplete(true);

                    // Save cleaned settings back to localStorage (without credentials)
                    localStorage.setItem('timeportal-settings', JSON.stringify(mergedSettings));

                    console.log('[SettingsContext] Settings loaded and migration complete');
                } catch (error) {
                    console.error('[SettingsContext] Failed to load from secure storage:', error);
                    // Fallback to localStorage values with hardcoded testing defaults
                    const mergedSettings = {
                        ...defaultSettings,
                        ...parsedSettings,
                        tempo: {
                            ...parsedSettings.tempo,
                            apiToken: defaultSettings.tempo.apiToken,
                            baseUrl: defaultSettings.tempo.baseUrl,
                            enabled: true,
                        },
                        jira: {
                            ...parsedSettings.jira,
                            baseUrl: defaultSettings.jira.baseUrl,
                            email: defaultSettings.jira.email,
                            apiToken: defaultSettings.jira.apiToken,
                            enabled: true,
                            selectedProjects: defaultSettings.jira.selectedProjects,
                        },
                    };
                    setSettings(mergedSettings);
                }
            } else {
                // Secure storage not available, use localStorage with hardcoded testing defaults
                const mergedSettings = {
                    ...defaultSettings,
                    ...parsedSettings,
                    tempo: {
                        ...parsedSettings.tempo,
                        apiToken: defaultSettings.tempo.apiToken,
                        baseUrl: defaultSettings.tempo.baseUrl,
                        enabled: true,
                    },
                    jira: {
                        ...parsedSettings.jira,
                        baseUrl: defaultSettings.jira.baseUrl,
                        email: defaultSettings.jira.email,
                        apiToken: defaultSettings.jira.apiToken,
                        enabled: true,
                        selectedProjects: defaultSettings.jira.selectedProjects,
                    },
                };
                setSettings(mergedSettings);
            }
        };

        if (isSecureStorageAvailable !== null) {
            loadAndMigrateSettings();
        }
    }, [isSecureStorageAvailable]);

    // Persist non-sensitive settings to localStorage
    useEffect(() => {
        if (migrationComplete) {
            // Only save non-sensitive settings to localStorage
            const settingsToSave = {
                ...settings,
                tempo: {
                    ...settings.tempo,
                    apiToken: '', // Don't save token to localStorage
                },
                jira: {
                    ...settings.jira,
                    email: '', // Don't save email to localStorage
                    apiToken: '', // Don't save token to localStorage
                },
            };
            localStorage.setItem('timeportal-settings', JSON.stringify(settingsToSave));
        }
    }, [settings, migrationComplete]);

    const updateSettings = async (updates: Partial<AppSettings>) => {
        // If secure storage is available and we're updating credentials, store them securely
        if (isSecureStorageAvailable) {
            try {
                if (updates.tempo?.apiToken && updates.tempo.apiToken !== defaultSettings.tempo.apiToken) {
                    await window.electron.ipcRenderer.secureStoreCredential('tempo-api-token', updates.tempo.apiToken);
                    console.log('[SettingsContext] Tempo API token stored securely');
                }

                if (updates.jira?.apiToken && updates.jira.apiToken !== defaultSettings.jira.apiToken) {
                    await window.electron.ipcRenderer.secureStoreCredential('jira-api-token', updates.jira.apiToken);
                    console.log('[SettingsContext] Jira API token stored securely');
                }

                if (updates.jira?.email && updates.jira.email !== defaultSettings.jira.email) {
                    await window.electron.ipcRenderer.secureStoreCredential('jira-email', updates.jira.email);
                    console.log('[SettingsContext] Jira email stored securely');
                }
            } catch (error) {
                console.error('[SettingsContext] Failed to store credentials securely:', error);
            }
        }

        setSettings(prev => ({ ...prev, ...updates }));
    };

    const resetSettings = async () => {
        // Delete stored credentials
        if (isSecureStorageAvailable) {
            try {
                await window.electron.ipcRenderer.secureDeleteCredential('tempo-api-token');
                await window.electron.ipcRenderer.secureDeleteCredential('jira-api-token');
                await window.electron.ipcRenderer.secureDeleteCredential('jira-email');
                console.log('[SettingsContext] Secure credentials deleted');
            } catch (error) {
                console.error('[SettingsContext] Failed to delete secure credentials:', error);
            }
        }

        setSettings(defaultSettings);
        localStorage.removeItem('timeportal-settings');
    };

    return (
        <SettingsContext.Provider value={{ settings, updateSettings, resetSettings }}>
            {children}
        </SettingsContext.Provider>
    );
};

export const useSettings = () => {
    const context = useContext(SettingsContext);
    if (!context) {
        throw new Error('useSettings must be used within a SettingsProvider');
    }
    return context;
};