import React, { createContext, useContext, useState, useEffect } from 'react';

export interface TempoWorkAttributeValue {
    key: string;
    value: string;
}

export interface TempoSettings {
    apiToken: string;
    baseUrl: string; // 'https://api.tempo.io' or 'https://api.eu.tempo.io'
    defaultIssueKey?: string; // Optional default Jira issue key
    enabled: boolean;
    workAttributes?: TempoWorkAttributeValue[]; // Configured work attributes
}

export interface JiraSettings {
    baseUrl: string; // 'https://your-domain.atlassian.net'
    email: string; // User email for basic auth
    apiToken: string; // Jira API token
    enabled: boolean;
    selectedProjects: string[]; // Array of project keys to fetch data from
    autoSync: boolean; // Enable automatic periodic sync
    syncInterval: number; // Sync interval in minutes (15, 30, 60, 120)
    lastSyncTimestamp: number; // Timestamp of last successful sync
}

export interface AISettings {
    autoGenerateDescription: boolean;  // Default: true
    autoAssignWork: boolean;           // Default: true
    autoSelectAccount: boolean;        // Default: true
}

export interface AppSettings {
    minActivityDuration: number; // milliseconds - activities shorter than this get filtered
    activityGapThreshold: number; // milliseconds - max gap between same-app activities to keep short ones
    timeRoundingIncrement: number; // minutes - round time entries up to this increment (1 = no rounding)
    tempo: TempoSettings;
    jira: JiraSettings;
    ai?: AISettings;
}

interface SettingsContextType {
    settings: AppSettings;
    updateSettings: (updates: Partial<AppSettings>) => void;
    resetSettings: () => void;
}

const defaultSettings: AppSettings = {
    minActivityDuration: 1000, // 1 second
    activityGapThreshold: 2 * 60 * 1000, // 2 minutes
    timeRoundingIncrement: 15, // 15 minutes default
    tempo: {
        apiToken: '',
        baseUrl: 'https://api.tempo.io',
        defaultIssueKey: '',
        enabled: false,
        workAttributes: [],
    },
    jira: {
        baseUrl: '',
        email: '',
        apiToken: '',
        enabled: false,
        selectedProjects: [],
        autoSync: true,
        syncInterval: 30, // 30 minutes default
        lastSyncTimestamp: 0,
    },
    ai: {
        autoGenerateDescription: true,
        autoAssignWork: true,
        autoSelectAccount: true,
    },
};

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

export const SettingsProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [settings, setSettings] = useState<AppSettings>(defaultSettings);
    const [isSecureStorageAvailable, setIsSecureStorageAvailable] = useState<boolean>(false);
    const [migrationComplete, setMigrationComplete] = useState<boolean>(false);

    // Helper function to save settings to database
    const saveSettingsToDatabase = async (settingsToSave: AppSettings) => {
        try {
            // Flatten settings for storage
            await window.electron.ipcRenderer.db.setSetting('minActivityDuration', settingsToSave.minActivityDuration);
            await window.electron.ipcRenderer.db.setSetting('activityGapThreshold', settingsToSave.activityGapThreshold);
            await window.electron.ipcRenderer.db.setSetting('timeRoundingIncrement', settingsToSave.timeRoundingIncrement);
            await window.electron.ipcRenderer.db.setSetting('tempo', settingsToSave.tempo);
            await window.electron.ipcRenderer.db.setSetting('jira', settingsToSave.jira);
            await window.electron.ipcRenderer.db.setSetting('ai', settingsToSave.ai);
            console.log('[SettingsContext] Settings saved to database');
        } catch (error) {
            console.error('[SettingsContext] Failed to save settings to database:', error);
        }
    };

    // Check if secure storage is available
    useEffect(() => {
        const checkSecureStorage = async () => {
            try {
                const result = await window.electron.ipcRenderer.secureIsAvailable();
                setIsSecureStorageAvailable(result.available);
                console.log('[SettingsContext] Secure storage available:', result.available);
            } catch (error) {
                console.error('[SettingsContext] Failed to check secure storage:', error);
                setIsSecureStorageAvailable(false);
            }
        };
        checkSecureStorage();
    }, []);

    // Load settings from database
    useEffect(() => {
        const loadAndMigrateSettings = async () => {
            console.log('[SettingsContext] Loading settings from database');
            let parsedSettings = defaultSettings;

            try {
                // Load all settings from database
                const allSettingsResult = await window.electron.ipcRenderer.db.getAllSettings();

            if (allSettingsResult.success && allSettingsResult.data) {
                const dbSettings = allSettingsResult.data;

                // Merge database settings with defaults
                if (Object.keys(dbSettings).length > 0) {
                    try {
                        // Convert flat key-value pairs back to nested structure
                        parsedSettings = {
                            ...defaultSettings,
                            minActivityDuration: dbSettings.minActivityDuration ?? defaultSettings.minActivityDuration,
                            activityGapThreshold: dbSettings.activityGapThreshold ?? defaultSettings.activityGapThreshold,
                            timeRoundingIncrement: dbSettings.timeRoundingIncrement ?? defaultSettings.timeRoundingIncrement,
                            tempo: {
                                ...defaultSettings.tempo,
                                ...(dbSettings.tempo || {})
                            },
                            jira: {
                                ...defaultSettings.jira,
                                ...(dbSettings.jira || {})
                            },
                            ai: {
                                ...defaultSettings.ai,
                                ...(dbSettings.ai || {})
                            }
                        };
                        console.log('[SettingsContext] Loaded settings from database');
                    } catch (error) {
                        console.error('[SettingsContext] Failed to parse settings from database:', error);
                        parsedSettings = defaultSettings;
                    }
                } else {
                    console.log('[SettingsContext] No settings in database, using defaults');
                }
            } else {
                console.error('[SettingsContext] Failed to load settings from database:', allSettingsResult.error);
            }

            // If secure storage is available, try to load credentials from secure storage
            if (isSecureStorageAvailable) {
                try {
                    // Migrate credentials from localStorage to secure storage if they exist
                    if (parsedSettings.tempo?.apiToken && parsedSettings.tempo.apiToken !== defaultSettings.tempo.apiToken) {
                        console.log('[SettingsContext] Migrating Tempo API token to secure storage');
                        await window.electron.ipcRenderer.secureStoreCredential('tempo-api-token', parsedSettings.tempo.apiToken);
                        // Clear from localStorage
                        parsedSettings.tempo.apiToken = '';
                    }

                    if (parsedSettings.jira?.apiToken && parsedSettings.jira.apiToken !== defaultSettings.jira.apiToken) {
                        console.log('[SettingsContext] Migrating Jira API token to secure storage');
                        await window.electron.ipcRenderer.secureStoreCredential('jira-api-token', parsedSettings.jira.apiToken);
                        // Clear from localStorage
                        parsedSettings.jira.apiToken = '';
                    }

                    if (parsedSettings.jira?.email && parsedSettings.jira.email !== defaultSettings.jira.email) {
                        console.log('[SettingsContext] Migrating Jira email to secure storage');
                        await window.electron.ipcRenderer.secureStoreCredential('jira-email', parsedSettings.jira.email);
                        // Clear from localStorage
                        parsedSettings.jira.email = '';
                    }

                    // Load credentials from secure storage
                    const tempoTokenResult = await window.electron.ipcRenderer.secureGetCredential('tempo-api-token');
                    const jiraTokenResult = await window.electron.ipcRenderer.secureGetCredential('jira-api-token');
                    const jiraEmailResult = await window.electron.ipcRenderer.secureGetCredential('jira-email');

                    console.log('[SettingsContext] Loaded credentials from secure storage:', {
                        tempoToken: tempoTokenResult.success && tempoTokenResult.value ? 'present' : 'absent',
                        jiraToken: jiraTokenResult.success && jiraTokenResult.value ? 'present' : 'absent',
                        jiraEmail: jiraEmailResult.success && jiraEmailResult.value ? 'present' : 'absent',
                    });

                    // Build settings with credentials from secure storage
                    const mergedSettings: AppSettings = {
                        ...defaultSettings,
                        ...parsedSettings,
                        tempo: {
                            ...parsedSettings.tempo,
                            // Use secure storage value if available, otherwise use default
                            apiToken: (tempoTokenResult.success && tempoTokenResult.value) || parsedSettings.tempo?.apiToken || defaultSettings.tempo.apiToken,
                            baseUrl: parsedSettings.tempo?.baseUrl || defaultSettings.tempo.baseUrl,
                            defaultIssueKey: parsedSettings.tempo?.defaultIssueKey || '',
                            enabled: parsedSettings.tempo?.enabled ?? defaultSettings.tempo.enabled,
                        },
                        jira: {
                            ...parsedSettings.jira,
                            // Use secure storage values if available, otherwise use defaults
                            baseUrl: parsedSettings.jira?.baseUrl || defaultSettings.jira.baseUrl,
                            email: (jiraEmailResult.success && jiraEmailResult.value) || parsedSettings.jira?.email || defaultSettings.jira.email,
                            apiToken: (jiraTokenResult.success && jiraTokenResult.value) || parsedSettings.jira?.apiToken || defaultSettings.jira.apiToken,
                            enabled: parsedSettings.jira?.enabled ?? defaultSettings.jira.enabled,
                            selectedProjects: parsedSettings.jira?.selectedProjects || defaultSettings.jira.selectedProjects,
                            autoSync: parsedSettings.jira?.autoSync ?? defaultSettings.jira.autoSync,
                            syncInterval: parsedSettings.jira?.syncInterval || defaultSettings.jira.syncInterval,
                            lastSyncTimestamp: parsedSettings.jira?.lastSyncTimestamp || defaultSettings.jira.lastSyncTimestamp,
                        },
                    };

                    setSettings(mergedSettings);
                    setMigrationComplete(true);

                    // Save cleaned settings to database (without credentials)
                    await saveSettingsToDatabase(mergedSettings);

                    console.log('[SettingsContext] Settings loaded and migration complete');
                } catch (error) {
                    console.error('[SettingsContext] Failed to load from secure storage:', error);
                    // Fallback to database values (which may have credentials from older versions)
                    const mergedSettings = {
                        ...defaultSettings,
                        ...parsedSettings,
                        tempo: {
                            ...defaultSettings.tempo,
                            ...parsedSettings.tempo,
                        },
                        jira: {
                            ...defaultSettings.jira,
                            ...parsedSettings.jira,
                        },
                    };
                    setSettings(mergedSettings);
                }
            } else {
                // Secure storage not available, use database values
                console.warn('[SettingsContext] Secure storage not available, using database values');
                const mergedSettings = {
                    ...defaultSettings,
                    ...parsedSettings,
                    tempo: {
                        ...defaultSettings.tempo,
                        ...parsedSettings.tempo,
                    },
                    jira: {
                        ...defaultSettings.jira,
                        ...parsedSettings.jira,
                    },
                };
                setSettings(mergedSettings);
            }
            } catch (error) {
                console.error('[SettingsContext] Error loading settings from database:', error);
                setSettings(defaultSettings);
            }
        };

        if (isSecureStorageAvailable !== null) {
            loadAndMigrateSettings();
        }
    }, [isSecureStorageAvailable]);

    // Persist non-sensitive settings to database
    useEffect(() => {
        if (migrationComplete) {
            // Only save non-sensitive settings to database
            const settingsToSave = {
                ...settings,
                tempo: {
                    ...settings.tempo,
                    apiToken: '', // Don't save token to database (use secure storage)
                },
                jira: {
                    ...settings.jira,
                    email: '', // Don't save email to database (use secure storage)
                    apiToken: '', // Don't save token to database (use secure storage)
                },
            };
            saveSettingsToDatabase(settingsToSave);
        }
    }, [settings, migrationComplete]);

    const updateSettings = async (updates: Partial<AppSettings>) => {
        // If secure storage is available and we're updating credentials, store them securely
        if (isSecureStorageAvailable) {
            try {
                if (updates.tempo?.apiToken && updates.tempo.apiToken !== defaultSettings.tempo.apiToken) {
                    await window.electron.ipcRenderer.secureStoreCredential('tempo-api-token', updates.tempo.apiToken);
                    console.log('[SettingsContext] Tempo API token stored securely');
                }

                if (updates.jira?.apiToken && updates.jira.apiToken !== defaultSettings.jira.apiToken) {
                    await window.electron.ipcRenderer.secureStoreCredential('jira-api-token', updates.jira.apiToken);
                    console.log('[SettingsContext] Jira API token stored securely');
                }

                if (updates.jira?.email && updates.jira.email !== defaultSettings.jira.email) {
                    await window.electron.ipcRenderer.secureStoreCredential('jira-email', updates.jira.email);
                    console.log('[SettingsContext] Jira email stored securely');
                }
            } catch (error) {
                console.error('[SettingsContext] Failed to store credentials securely:', error);
            }
        }

        setSettings(prev => ({ ...prev, ...updates }));
    };

    const resetSettings = async () => {
        // Delete stored credentials
        if (isSecureStorageAvailable) {
            try {
                await window.electron.ipcRenderer.secureDeleteCredential('tempo-api-token');
                await window.electron.ipcRenderer.secureDeleteCredential('jira-api-token');
                await window.electron.ipcRenderer.secureDeleteCredential('jira-email');
                console.log('[SettingsContext] Secure credentials deleted');
            } catch (error) {
                console.error('[SettingsContext] Failed to delete secure credentials:', error);
            }
        }

        // Delete settings from database
        try {
            await window.electron.ipcRenderer.db.deleteSetting('minActivityDuration');
            await window.electron.ipcRenderer.db.deleteSetting('activityGapThreshold');
            await window.electron.ipcRenderer.db.deleteSetting('timeRoundingIncrement');
            await window.electron.ipcRenderer.db.deleteSetting('tempo');
            await window.electron.ipcRenderer.db.deleteSetting('jira');
            await window.electron.ipcRenderer.db.deleteSetting('ai');
            console.log('[SettingsContext] Settings deleted from database');
        } catch (error) {
            console.error('[SettingsContext] Failed to delete settings from database:', error);
        }

        setSettings(defaultSettings);
    };

    return (
        <SettingsContext.Provider value={{ settings, updateSettings, resetSettings }}>
            {children}
        </SettingsContext.Provider>
    );
};

export const useSettings = () => {
    const context = useContext(SettingsContext);
    if (!context) {
        throw new Error('useSettings must be used within a SettingsProvider');
    }
    return context;
};